[server]
runOnSave = true
folderWatchList = ["calc_package/core"]

[theme]
primaryColor = "#C2662D"
backgroundColor = "#FAF7F2"
secondaryBackgroundColor = "#EDE4D8"
textColor = "#3D362F"
font = "serif"